
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

destinations:
  queues:
    NYSE:
      exchange: nyse
      routing-key: NYSE
  topics:
    weather:
      exchange: alerts
      routing-key: WEATHER